// <auto-generated />
using HotelInformationSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelInformationSystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HotelInformationSystem.Data.Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Name = "Ethiopia",
                            ShortName = "ET"
                        },
                        new
                        {
                            id = 2,
                            Name = "Kenya",
                            ShortName = "KN"
                        },
                        new
                        {
                            id = 3,
                            Name = "Sudan",
                            ShortName = "SN"
                        });
                });

            modelBuilder.Entity("HotelInformationSystem.Data.Hotel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Address = "Addis Ababa",
                            CountryId = 1,
                            Name = "Ilily Hotel",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            id = 2,
                            Address = "Nairobi",
                            CountryId = 2,
                            Name = "Sheraton Hotel",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            id = 3,
                            Address = "Khartum",
                            CountryId = 3,
                            Name = "Hilton",
                            Rating = 4.9000000000000004
                        });
                });

            modelBuilder.Entity("HotelInformationSystem.Data.Hotel", b =>
                {
                    b.HasOne("HotelInformationSystem.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
